config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  get 'home/about'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root 'home#index'
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_footer.html.erb
<footer>
    <div class="footer-info">
        <div class="d-flex justify-content-sm-evenly">
            
            <div class="p-2">
                Contact Us
            </div>
            
            <div class="p-2">
                Contact Us
            </div>
            
            <div class="p-2">
                Contact Us
            </div>
        </div>
    </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'Panda', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'About Panda', home_about_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Other', root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">THIRD</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            FOURTH WITH DROPDOWN
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About...</h1>

app/views/home/index.html.erb
<div class="body-index">
    <div class="d-flex flex-column mb-3 justify-content-center">

        <div class="p-2">
            Best Panda Ever! (Bocce...duh!)
        </div>
        
        <div class="p-2">
            ...
        </div>
        
        <div class="p-2">
            ...
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Test Site</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
  <div class="background-pic">
    <%= image_tag("IMG_5199.jpg", class: "img-fluid") %>
  </div>
    <div>
      <div>
        <%= render 'home/header' %>
        </br>
      </div>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
      </div>
      <%= yield %>
      <%= render 'home/footer' %>
    </body>
</html>